# Generated by Django 2.1.8 on 2019-06-06 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=10)),
                ('category_name', models.CharField(max_length=255)),
                ('category_desc', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='GlobalMarkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_cost_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('labor_retail_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('asst_labor_cost_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('asst_labor_retail_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('misc_tos_cost_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('misc_tos_retail_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('standard_labor_markup_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('standard_material_markup_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('standard_total_markup_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('labor_tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('parts_tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('invoice_tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=10)),
                ('job_name', models.CharField(choices=[('Drain Cleaning', 'Drain Cleaning'), ('Plumbing', 'Plumbing'), ('Water Heater', 'Water Heater'), ('Misc', 'Misc')], max_length=25)),
                ('job_desc', models.CharField(blank=True, max_length=255)),
                ('ordering_num', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('job_id',),
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('master_part_num', models.CharField(blank=True, max_length=10)),
                ('mfg_part_num', models.CharField(blank=True, max_length=10)),
                ('upc_num', models.CharField(blank=True, max_length=10)),
                ('part_desc', models.CharField(blank=True, max_length=255)),
                ('base_part_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Empty input defaults to 0.00.', max_digits=10)),
                ('markup_percent_id', models.CharField(blank=True, max_length=100)),
                ('set_custom_part_cost', models.BooleanField(default=False)),
                ('custom_retail_part_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Empty input defaults to 0.', max_digits=10)),
                ('retail_part_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Empty input defaults to 0.00.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('master_part_num',),
            },
        ),
        migrations.CreateModel(
            name='PartsMarkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_low', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('range_high', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='TagTypesChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(choices=[('Drain Cleaning', 'Drain Cleaning'), ('Plumbing', 'Plumbing'), ('Water Heater', 'Water Heater'), ('Misc', 'Misc')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=10)),
                ('task_name', models.CharField(blank=True, max_length=255)),
                ('task_desc', models.CharField(blank=True, max_length=255)),
                ('task_comments', models.CharField(blank=True, max_length=255)),
                ('task_attribute', models.CharField(choices=[('Task Only', 'Task Only'), ('Addon Only', 'Addon Only'), ('Addon and Task', 'Addon and Task')], default='Task Only', max_length=15)),
                ('estimated_contractor_hours', models.FloatField(default=0.0, help_text='2.0 represents 2 hours. \n Empty input defaults to 0.0 in db. ')),
                ('estimated_contractor_minutes', models.FloatField(default=0.0, help_text='2.5 represets 2 minutes 30 seconds. \n Empty input defaults to 0.0 in db.')),
                ('estimated_asst_hours', models.FloatField(default=0.0, help_text='2.0 represents 2 hours. \n Empty input defaults to 0.0 in db.')),
                ('estimated_asst_minutes', models.FloatField(default=0.0, help_text='2.5 represets 2 minutes 30 seconds. \n Empty input defaults to 0.0 in db.')),
                ('fixed_labor_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Empty input defaults to 0.00.', max_digits=10)),
                ('use_fixed_labor_rate', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Categories')),
            ],
            options={
                'ordering': ('task_id',),
            },
        ),
        migrations.CreateModel(
            name='TasksParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Parts')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Tasks')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='parts',
            field=models.ManyToManyField(through='inventory.TasksParts', to='inventory.Parts'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='tag_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.TagTypesChoices'),
        ),
        migrations.AddField(
            model_name='parts',
            name='tag_types',
            field=models.ManyToManyField(to='inventory.TagTypesChoices'),
        ),
        migrations.AddField(
            model_name='globalmarkup',
            name='tag_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.TagTypesChoices'),
        ),
        migrations.AddField(
            model_name='categories',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Jobs'),
        ),
        migrations.AlterUniqueTogether(
            name='tasksparts',
            unique_together={('task', 'part')},
        ),
    ]
