# Generated by Django 2.1.11 on 2019-08-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190809_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_attribute',
            field=models.CharField(choices=[('Task Only', 'Task Only'), ('Addon Only', 'Addon Only'), ('Addon And Task', 'Addon And Task')], default='Task Only', max_length=15),
        ),
    ]
